#!/usr/bin/env node
/**
 * Resolves the prototype's relative-oklch palette into static hex values.
 *
 * The design uses `oklch(from var(--x) L C h)`, which Safari and older Android
 * WebViews do not support. This precomputes static hex so the brand colours
 * never degrade.
 *
 * Writes app/assets/css/_generated-palette.css, imported by tokens.css.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../app/assets/css/_generated-palette.css')

/** sRGB channel -> linear-light */
const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
const linearToSrgb = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055)

function hexToOklch(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => srgbToLinear(parseInt(hex.slice(i, i + 2), 16) / 255))
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s
  return { L, C: Math.hypot(A, B), h: (Math.atan2(B, A) * 180) / Math.PI }
}

function oklchToHex(L, C, hDeg) {
  const h = (hDeg * Math.PI) / 180
  const A = C * Math.cos(h)
  const B = C * Math.sin(h)
  const l = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3
  const m = (L - 0.1055613458 * A - 0.0638541728 * B) ** 3
  const s = (L - 0.0894841775 * A - 1.291485548 * B) ** 3
  const rgb = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ]
  return (
    '#' +
    rgb
      .map((c) => Math.round(Math.min(1, Math.max(0, linearToSrgb(c))) * 255).toString(16).padStart(2, '0'))
      .join('')
  )
}

// Base colours and the L/C ramps, copied verbatim from the prototype.
const CHARCOAL = '#282d30'
const GOLD = '#f7e499'
const NEUTRAL = {
  100: [0.97, 0.002],
  200: [0.92, 0.003],
  300: [0.82, 0.004],
  400: [0.65, 0.005],
  500: [0.48, 0.006],
  600: [0.34, 0.006],
  700: [0.26, 0.005],
}
const GOLD_RAMP = { 100: [0.96, 0.03], 300: [0.82, 0.09] }

const charcoalHue = hexToOklch(CHARCOAL).h
const goldHue = hexToOklch(GOLD).h

// Emitted as `@theme static` rather than `:root` so the ramp overrides
// Tailwind's stock neutral palette, generates utilities (bg-neutral-500, etc.)
// and survives Tailwind's default tree-shaking of unreferenced theme vars.
const lines = ['/* GENERATED by scripts/compute-oklch.mjs — do not edit. */', '@theme static {']
for (const [step, [L, C]] of Object.entries(NEUTRAL)) {
  lines.push(`  --color-neutral-${step}: ${oklchToHex(L, C, charcoalHue)};`)
}
for (const [step, [L, C]] of Object.entries(GOLD_RAMP)) {
  lines.push(`  --color-gold-${step}: ${oklchToHex(L, C, goldHue)};`)
}
lines.push(`  --color-brass-500: ${oklchToHex(0.62, 0.11, 75)};`)
lines.push(`  --color-brass-700: ${oklchToHex(0.42, 0.09, 55)};`)
lines.push(`  --color-success-500: ${oklchToHex(0.6, 0.1, 145)};`)
lines.push(`  --color-warning-500: ${oklchToHex(0.75, 0.13, 75)};`)
lines.push(`  --color-danger-500: ${oklchToHex(0.55, 0.16, 25)};`)
lines.push('}')

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, lines.join('\n') + '\n')
console.log(`wrote ${OUT}`)
console.log(lines.filter((l) => l.includes('--color')).join('\n'))
